#!/bin/bash

fail() {
  echo "$@" >&2
  exit 1
}

setup_curl() {
  head() {
    curl --head --silent "$@"
  }
  get() {
    curl --insecure --location --remote-name "$@"
  }
}

setup_wget() {
  head() {
    wget --server-response --quiet --output-document=/dev/null "$@" 2>&1
  }
  get() {
    wget "$@"
  }
}

filter_tag() {
  xargs basename
}

filter_location() {
  awk '/Location:/{print $2}' | tr -d '\r' 
}

ask_github() {
  head https://github.com/exercism/cli/releases/latest
}

latest() {
  ask_github | filter_location | filter_tag
}

archive_os() {
  case "$(uname -s)" in
  Darwin) echo "darwin" ;;
  *)      echo "linux" ;;
  esac
}

archive_arch() {
  case "$(uname -m)" in
  x86_64) echo "amd64" ;;
  *)      echo "i386" ;;
  esac
}

archive() {
  echo "exercism-$(archive_os)-$(archive_arch).tgz"
}

if type curl &>/dev/null; then
  setup_curl
elif type wget &>/dev/null; then
  setup_wget
else
  fail "error: please install \`curl\` or \`wget\` and try again"
fi

VERSION="$(latest)"
FILE="$(archive)"
URL=https://github.com/exercism/cli/releases/download/$VERSION/$FILE
cd /tmp
get $URL ||
fail "Unable to download $URL"

tar zxvf $FILE ||
fail "Failed to unpack $FILE"

if [ -d /usr/local/bin ]; then
  if [ -w /usr/local/bin ]; then
    mv exercism /usr/local/bin/
  fi
fi

if [ ! -f /usr/local/bin/exercism ]; then
  # OK. Trying something else.
  # This might be considered slightly impolite.
  if [ ! -d $HOME/bin ]; then
    mkdir $HOME/bin
  fi
  mv exercism $HOME/bin/

  if [ $? != 0 ]; then
    echo "Unable to figure out where to put the binary"
    echo "Please submit an issue so we can improve the script: https://github.com/exercism/cli-www/issues"
    exit 1
  fi
fi

if [ ! $(echo $PATH | grep "$HOME/bin") ]; then
  if [ ! $(echo $PATH | grep "~/bin") ]; then
    # Add ~/bin to the PATH
    if [ -f $HOME/.bash_profile ]; then
      echo 'export PATH=$HOME/bin:$PATH' >> $HOME/.bash_profile
    fi
    if [ -f $HOME/.zshrc ]; then
      echo 'export PATH=$HOME/bin:$PATH' >> $HOME/.zshrc
    fi
  fi
fi
