#!/bin/bash

filter_tag() {
  xargs basename
}

head() {
  curl --head --silent "$@"
}

ask_github() {
  head https://github.com/exercism/cli/releases/latest
}

latest() {
  ask_github | grep Location | awk '{print $2}' | filter_tag | tr -d '\r'
}

VERSION="$(latest)"

if [ "$(uname -s)" == "Darwin" ]; then
  OS="darwin"
else
  OS="linux"
fi

if [ "$(uname -m)" == "x86_64" ]; then
  FILE="exercism-$OS-amd64.tgz"
else
  FILE="exercism-$OS-i386.tgz"
fi

cd /tmp

URL=https://github.com/exercism/cli/releases/download/$VERSION/$FILE

if type curl &>/dev/null; then
  curl -LOk $URL
elif type wget &>/dev/null; then
  wget $URL
else
  echo "error: please install \`curl\` or \`wget\` and try again" >&2
  exit 1
fi

if [ $? != 0 ]; then
  echo "Unable to download $URL"
  exit 1
fi

tar zxvf $FILE

if [ $? != 0 ]; then
  echo "Failed to unpack $FILE"
  exit 1
fi

if [ -d /usr/local/bin ]; then
  if [ -w /usr/local/bin ]; then
    mv exercism /usr/local/bin/
  fi
fi

if [ ! -f /usr/local/bin/exercism ]; then
  # OK. Trying something else.
  # This might be considered slightly impolite.
  if [ ! -d $HOME/bin ]; then
    mkdir $HOME/bin
  fi
  mv exercism $HOME/bin/

  if [ $? != 0 ]; then
    echo "Unable to figure out where to put the binary"
    echo "Please submit an issue so we can improve the script: https://github.com/exercism/cli-www/issues"
    exit 1
  fi
fi

if [ ! $(echo $PATH | grep "$HOME/bin") ]; then
  if [ ! $(echo $PATH | grep "~/bin") ]; then
    # Add ~/bin to the PATH
    if [ -f $HOME/.bash_profile ]; then
      echo 'export PATH=$HOME/bin:$PATH' >> $HOME/.bash_profile
    fi
    if [ -f $HOME/.zshrc ]; then
      echo 'export PATH=$HOME/bin:$PATH' >> $HOME/.zshrc
    fi
  fi
fi
